mcpServers:
  Roblox_Studio:
    command: /Applications/RobloxStudio.app/Contents/MacOS/StudioMCP

  blender:
    command: uv
    args:
      - "--directory"
      - "$HOME/blender_mcp/mcp"
      - run
      - blender-mcp
